lsi: false
safe: true
remote_theme: pmarsceill/just-the-docs
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
